version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartemr
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/smartemr
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USE_AUTH=true
      - UPLOAD_DIR=/app/uploads
    ports:
      - "8001:8001"
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
      - ./firebase_service_account.json:/app/firebase_service_account.json:ro

volumes:
  pgdata:
